kind = "web"
previewPath = "/"
title = "Gestão Empresarial"
version = "1.0.0"
id = "artifacts/gestao-empresarial"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20526

[services.development]
run = "pnpm --filter @workspace/gestao-empresarial run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gestao-empresarial", "run", "build" ]
publicDir = "artifacts/gestao-empresarial/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20526"
BASE_PATH = "/"
